server:
  port: 8080

spring:
  application:
    name: ebanking-dlt-retry-java

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-svc:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    consumer:
      group-id: dlt-retry-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: com.data2ai.kafka.dltretry.model,com.data2ai.kafka.*

app:
  kafka:
    topic: banking.transactions
    dlt-topic: banking.transactions.dlq

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
