server:
  port: 8080

spring:
  application:
    name: ebanking-idempotent-producer-java

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-svc:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 2147483647
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 10
        batch.size: 16384
        compression.type: snappy

app:
  kafka:
    topic: banking.transactions

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
