server:
  port: 8080

spring:
  application:
    name: ebanking-transactions-java

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-svc:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        transactional.id: ebanking-tx
    consumer:
      group-id: transaction-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        isolation.level: read_committed
        spring.json.trusted.packages: com.data2ai.kafka.transactions.model

app:
  kafka:
    topic: banking.transactions
    transactional-id: ebanking-tx

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
