apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebanking-transactional-api
  namespace: ${NAMESPACE}
  labels:
    app: ebanking-transactional-api
    module: m04-transactions
    day: day-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebanking-transactional-api
  template:
    metadata:
      labels:
        app: ebanking-transactional-api
    spec:
      containers:
        - name: ebanking-transactional-api
          image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/ebanking-transactional-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8080"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: Kafka__BootstrapServers
              value: "kafka-svc:9092"
            - name: Kafka__Topic
              value: "banking.transactions"
            - name: Kafka__TransactionalId
              value: "ebanking-payment-producer"
          readinessProbe:
            httpGet:
              path: /api/transactions/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/transactions/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ebanking-transactional-api
  namespace: ${NAMESPACE}
  labels:
    app: ebanking-transactional-api
spec:
  selector:
    app: ebanking-transactional-api
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ebanking-transactional-api-secure
  namespace: ${NAMESPACE}
spec:
  to:
    kind: Service
    name: ebanking-transactional-api
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
